stages:
  - name: sum_coeffs
    steps:
      - name: add_coeffs
        resources:
          - sum_coeffs.py
        inputs: [ poly_0.out, poly_1.out, poly_2.out ]
        outputs: [ poly_sum.out ]
        jobs:
          - name: sum_up
            executable: sum_coeffs.py
            args: [ ]

  - name: calculate_coeffs
    steps:
      - name: zero_degree
        resources:
          - evaluate_coeffs.py
        inputs: [poly_2.out]
        outputs: [poly_0.out]
        jobs:
          - name: generate_zero_degree
            executable: evaluate_coeffs.py
            args: ["0"]

      - name: first_degree
        resources:
          - evaluate_coeffs.py
        outputs: [poly_1.out]
        jobs:
          - name: generate_first_degree
            executable: evaluate_coeffs.py
            args: ["1"]

      - name: second_degree
        resources:
          - evaluate_coeffs.py
        outputs: [poly_2.out]
        jobs:
          - name: generate_second_degree
            executable: evaluate_coeffs.py
            args: ["2"]



realizations: 25
max_running: 6
max_retries: 2
run_path: my_output
executor: local
storage:
  type: shared_disk
  storage_path: .my_storage
