name: Run polynomial demo 

on: [push, pull_request]

jobs:
  build:
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install ERT
      run: |
        pip install .

    - name: Run polynomial demo
      run: |
        ert3 init --example polynomial
        pushd polynomial
        ./run_demo
        popd
